=begin
#MyMarketing Notifications

#Virtuoso MyMarketing Notification API

OpenAPI spec version: 1.0.0
Contact: techappdev@virtuoso.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

require 'spec_helper'
require 'json'

# Unit tests for MyMarketing::NotificationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'NotificationApi' do
  before do
    # run before each test
    @instance = MyMarketing::NotificationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NotificationApi' do
    it 'should create an instance of NotificationApi' do
      expect(@instance).to be_instance_of(MyMarketing::NotificationApi)
    end
  end

  # unit tests for notifications_post
  # Queue a notification
  # Queues a notification to be sent on sendDate
  # @param body Notification that needs to be added to the queue
  # @param [Hash] opts the optional parameters
  # @return [NotificationResponse]
  describe 'notifications_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
