=begin
#MyMarketing Notifications

#Virtuoso MyMarketing Notification API

OpenAPI spec version: 1.0.0
Contact: techappdev@virtuoso.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

# Common files
require 'my_marketing/api_client'
require 'my_marketing/api_error'
require 'my_marketing/version'
require 'my_marketing/configuration'

# Models
require 'my_marketing/models/consumer_create'
require 'my_marketing/models/consumer_response'
require 'my_marketing/models/consumer_result'
require 'my_marketing/models/consumer_update'
require 'my_marketing/models/custom_data'
require 'my_marketing/models/login_response'
require 'my_marketing/models/login_result'
require 'my_marketing/models/notification'
require 'my_marketing/models/notification_response'

# APIs
require 'my_marketing/api/consumer_api'
require 'my_marketing/api/login_api'
require 'my_marketing/api/notification_api'

module MyMarketing
  class << self
    # Customize default settings for the SDK using block.
    #   MyMarketing.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
