=begin
#MyMarketing Notifications

#Virtuoso MyMarketing Notification API

OpenAPI spec version: 1.0.0
Contact: techappdev@virtuoso.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

require 'uri'

module MyMarketing
  class LoginApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Authentication
    # Generate an encrpted token as described by the JavaScript on this fiddle: https://jsfiddle.net/VirtuosoEngineering/xyrzc06n/. Confirm the token generated by the JavaScript matches the token generated by your programming language before proceeding. See https://api.virtuoso.com/documentation for more information.
    # @param user API user name
    # @param auth_token Encrypted auth token generated as per instructions above
    # @param [Hash] opts the optional parameters
    # @return [LoginResponse]
    def login_get(user, auth_token, opts = {})
      data, _status_code, _headers = login_get_with_http_info(user, auth_token, opts)
      data
    end

    # Authentication
    # Generate an encrpted token as described by the JavaScript on this fiddle: https://jsfiddle.net/VirtuosoEngineering/xyrzc06n/. Confirm the token generated by the JavaScript matches the token generated by your programming language before proceeding. See https://api.virtuoso.com/documentation for more information.
    # @param user API user name
    # @param auth_token Encrypted auth token generated as per instructions above
    # @param [Hash] opts the optional parameters
    # @return [Array<(LoginResponse, Fixnum, Hash)>] LoginResponse data, response status code and response headers
    def login_get_with_http_info(user, auth_token, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: LoginApi.login_get ...'
      end
      # verify the required parameter 'user' is set
      if @api_client.config.client_side_validation && user.nil?
        fail ArgumentError, "Missing the required parameter 'user' when calling LoginApi.login_get"
      end
      # verify the required parameter 'auth_token' is set
      if @api_client.config.client_side_validation && auth_token.nil?
        fail ArgumentError, "Missing the required parameter 'auth_token' when calling LoginApi.login_get"
      end
      # resource path
      local_var_path = '/login'

      # query parameters
      query_params = {}
      query_params[:'user'] = user
      query_params[:'authToken'] = auth_token

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'LoginResponse')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: LoginApi#login_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
