=begin
#MyMarketing Notifications

#Virtuoso MyMarketing Notification API

OpenAPI spec version: 1.0.0
Contact: techappdev@virtuoso.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.8

=end

require 'uri'

module MyMarketing
  class NotificationApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Queue a notification
    # Queues a notification to be sent on sendDate
    # @param body Notification that needs to be added to the queue
    # @param [Hash] opts the optional parameters
    # @return [NotificationResponse]
    def notifications_post(body, opts = {})
      data, _status_code, _headers = notifications_post_with_http_info(body, opts)
      data
    end

    # Queue a notification
    # Queues a notification to be sent on sendDate
    # @param body Notification that needs to be added to the queue
    # @param [Hash] opts the optional parameters
    # @return [Array<(NotificationResponse, Fixnum, Hash)>] NotificationResponse data, response status code and response headers
    def notifications_post_with_http_info(body, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: NotificationApi.notifications_post ...'
      end
      # verify the required parameter 'body' is set
      if @api_client.config.client_side_validation && body.nil?
        fail ArgumentError, "Missing the required parameter 'body' when calling NotificationApi.notifications_post"
      end
      # resource path
      local_var_path = '/notifications'

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(body)
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'NotificationResponse')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: NotificationApi#notifications_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
